'use strict';
/* ============ 核心中英映射表(文件名基名 → 中文) ============ */
const ZH = {
/* ---- 方块 ---- */
stone:'石头',deepslate:'深板岩',granite:'花岗岩',diorite:'闪长岩',andesite:'安山岩',tuff:'凝灰岩',calcite:'方解石',basalt:'玄武岩',blackstone:'黑石',cobblestone:'圆石',mossy_cobblestone:'苔石',dirt:'泥土',coarse_dirt:'砂土',rooted_dirt:'缠根泥土',grass_block:'草方块',podzol:'灰化土',mycelium:'菌丝体',mud:'泥巴',packed_mud:'泥坯',muddy_mangrove_roots:'泥泞的红树根',sand:'沙子',red_sand:'红沙',gravel:'砂砾',clay:'黏土块',soul_sand:'灵魂沙',soul_soil:'灵魂土',
oak_log:'橡木原木',spruce_log:'云杉原木',birch_log:'白桦原木',jungle_log:'丛林原木',acacia_log:'金合欢原木',dark_oak_log:'深色橡木原木',mangrove_log:'红树原木',cherry_log:'樱花原木',bamboo_block:'竹块',oak_planks:'橡木木板',spruce_planks:'云杉木板',birch_planks:'白桦木板',jungle_planks:'丛林木板',acacia_planks:'金合欢木板',dark_oak_planks:'深色橡木木板',mangrove_planks:'红树木板',cherry_planks:'樱花木板',bamboo_planks:'竹木板',bamboo_mosaic:'竹马赛克',oak_leaves:'橡树树叶',spruce_leaves:'云杉树叶',birch_leaves:'白桦树叶',jungle_leaves:'丛林树叶',acacia_leaves:'金合欢树叶',dark_oak_leaves:'深色橡树树叶',mangrove_leaves:'红树树叶',cherry_leaves:'樱花树叶',azalea_leaves:'杜鹃树叶',flowering_azalea_leaves:'盛开的杜鹃树叶',
coal_ore:'煤矿石',iron_ore:'铁矿石',copper_ore:'铜矿石',gold_ore:'金矿石',redstone_ore:'红石矿石',lapis_ore:'青金石矿石',diamond_ore:'钻石矿石',emerald_ore:'绿宝石矿石',deepslate_coal_ore:'深层煤矿石',deepslate_iron_ore:'深层铁矿石',deepslate_copper_ore:'深层铜矿石',deepslate_gold_ore:'深层金矿石',deepslate_redstone_ore:'深层红石矿石',deepslate_lapis_ore:'深层青金石矿石',deepslate_diamond_ore:'深层钻石矿石',deepslate_emerald_ore:'深层绿宝石矿石',nether_quartz_ore:'下界石英矿石',nether_gold_ore:'下界金矿石',ancient_debris:'远古残骸',
coal_block:'煤炭块',iron_block:'铁块',gold_block:'金块',diamond_block:'钻石块',emerald_block:'绿宝石块',lapis_block:'青金石块',redstone_block:'红石块',copper_block:'铜块',netherite_block:'下界合金块',amethyst_block:'紫水晶块',budding_amethyst:'紫水晶母岩',raw_iron_block:'粗铁块',raw_copper_block:'粗铜块',raw_gold_block:'粗金块',
glass:'玻璃',tinted_glass:'遮光玻璃',glass_pane:'玻璃板',white_stained_glass:'白色染色玻璃',orange_stained_glass:'橙色染色玻璃',magenta_stained_glass:'品红色染色玻璃',light_blue_stained_glass:'淡蓝色染色玻璃',yellow_stained_glass:'黄色染色玻璃',lime_stained_glass:'黄绿色染色玻璃',pink_stained_glass:'粉红色染色玻璃',gray_stained_glass:'灰色染色玻璃',light_gray_stained_glass:'淡灰色染色玻璃',cyan_stained_glass:'青色染色玻璃',purple_stained_glass:'紫色染色玻璃',blue_stained_glass:'蓝色染色玻璃',brown_stained_glass:'棕色染色玻璃',green_stained_glass:'绿色染色玻璃',red_stained_glass:'红色染色玻璃',black_stained_glass:'黑色染色玻璃',
white_wool:'白色羊毛',red_wool:'红色羊毛',blue_wool:'蓝色羊毛',green_wool:'绿色羊毛',yellow_wool:'黄色羊毛',orange_wool:'橙色羊毛',purple_wool:'紫色羊毛',pink_wool:'粉红色羊毛',black_wool:'黑色羊毛',gray_wool:'灰色羊毛',light_gray_wool:'淡灰色羊毛',cyan_wool:'青色羊毛',magenta_wool:'品红色羊毛',lime_wool:'黄绿色羊毛',brown_wool:'棕色羊毛',light_blue_wool:'淡蓝色羊毛',white_concrete:'白色混凝土',red_concrete:'红色混凝土',blue_concrete:'蓝色混凝土',green_concrete:'绿色混凝土',yellow_concrete:'黄色混凝土',black_concrete:'黑色混凝土',gray_concrete:'灰色混凝土',white_terracotta:'白色陶瓦',terracotta:'陶瓦',white_glazed_terracotta:'白色带釉陶瓦',
bricks:'红砖块',stone_bricks:'石砖',deepslate_bricks:'深板岩砖',deepslate_tiles:'深板岩瓦',polished_blackstone_bricks:'磨制黑石砖',nether_bricks:'下界砖块',red_nether_bricks:'红色下界砖块',end_stone_bricks:'末地石砖',purpur_block:'紫珀块',quartz_block:'石英块',quartz_bricks:'石英砖',chiseled_quartz_block:'錾制石英块',prismarine:'海晶石',prismarine_bricks:'海晶石砖',dark_prismarine:'暗海晶石',smooth_stone:'平滑石头',smooth_quartz:'平滑石英',smooth_sandstone:'平滑砂岩',smooth_red_sandstone:'平滑红砂岩',sandstone:'砂岩',red_sandstone:'红砂岩',cut_sandstone:'切制砂岩',cut_copper:'切制铜',oxidized_copper:'氧化的铜',weathered_copper:'斑驳的铜',exposed_copper:'裸露的铜',waxed_copper_block:'涂蜡铜块',copper_bulb:'铜灯',chiseled_stone:'錾制石头',cracked_stone_bricks:'裂纹石砖',mossy_stone_bricks:'苔石砖',chiseled_stone_bricks:'錾制石砖',
crafting_table:'工作台',furnace:'熔炉',blast_furnace:'高炉',smoker:'烟熏炉',anvil:'铁砧',chipped_anvil:'开裂的铁砧',damaged_anvil:'损坏的铁砧',grindstone:'砂轮',stonecutter:'切石机',smithing_table:'锻造台',fletching_table:'制箭台',cartography_table:'制图台',loom:'织布机',enchanting_table:'附魔台',bookshelf:'书架',chiseled_bookshelf:'錾制书架',lectern:'讲台',chest:'箱子',trapped_chest:'陷阱箱',ender_chest:'末影箱',barrel:'木桶',hopper:'漏斗',dispenser:'发射器',dropper:'投掷器',observer:'侦测器',piston:'活塞',sticky_piston:'黏性活塞',piston_head:'活塞头',moving_piston:'移动的活塞',beacon:'信标',conduit:'潮涌核心',jukebox:'唱片机',note_block:'音符盒',respawn_anchor:'重生锚',lodestone:'磁石',spawner:'刷怪笼',crafter:'合成器',vault:'宝库',decorated_pot:'饰纹陶罐',campfire:'营火',soul_campfire:'灵魂营火',beehive:'蜂箱',beehive_end:'蜂箱(末)',bee_nest:'蜂巢',farmland:'耕地',hay_block:'干草块',dried_kelp_block:'干海带块',honeycomb_block:'蜜脾块',sponge:'海绵',wet_sponge:'湿海绵',slime_block:'黏液块',honey_block:'蜂蜜块',mushroom_block:'蘑菇方块',red_mushroom_block:'红色蘑菇方块',brown_mushroom_block:'棕色蘑菇方块',mushroom_stem:'蘑菇柄',nether_wart_block:'下界疣块',warped_wart_block:'诡异疣块',shroomlight:'菌光体',sea_lantern:'海晶灯',glowstone:'荧石',jack_o_lantern:'南瓜灯',carved_pumpkin:'雕刻过的南瓜',pumpkin:'南瓜',melon:'西瓜',cactus:'仙人掌',sugar_cane:'甘蔗',wheat:'小麦',carrots:'胡萝卜',potatoes:'马铃薯',beetroots:'甜菜根',nether_wart:'下界疣',cocoa:'可可果',torchflower:'火把花',pitcher_plant:'瓶子草',
redstone_lamp:'红石灯',redstone_torch:'红石火把',repeater:'红石中继器',comparator:'红石比较器',redstone_wire:'红石粉',lever:'拉杆',tripwire_hook:'绊线钩',pressure_plate:'压力板',weighted_pressure_plate:'测重压力板',button:'按钮',target:'标靶',daylight_detector:'阳光探测器',lightning_rod:'避雷针',tnt:'TNT',tnt_side:'TNT(侧)',rail:'铁轨',powered_rail:'动力铁轨',detector_rail:'探测铁轨',activator_rail:'激活铁轨',chain_command_block:'连锁命令方块',repeating_command_block:'循环命令方块',command_block:'命令方块',command_block_side:'命令方块(侧)',structure_block:'结构方块',structure_void:'结构空位',barrier:'屏障',jigsaw:'拼图方块',scaffolding:'脚手架',cauldron:'炼药锅',water_cauldron:'水瓶炼药锅',lava_cauldron:'熔岩炼药锅',powder_snow_cauldron:'细雪炼药锅',composter:'堆肥桶',bell:'钟',lightning_rod_on:'避雷针(激活)',cake:'蛋糕',candle:'蜡烛',sea_pickle:'海泡菜',turtle_egg:'海龟蛋',sniffer_egg:'嗅探兽蛋',frogspawn:'蛙卵',
white_bed:'白色床',red_bed:'红色床',blue_bed:'蓝色床',white_carpet:'白色地毯',moss_carpet:'苔藓地毯',white_banner:'白色旗帜',oak_door:'橡木门',iron_door:'铁门',oak_trapdoor:'橡木活板门',iron_trapdoor:'铁活板门',oak_fence:'橡木栅栏',oak_fence_gate:'橡木栅栏门',oak_stairs:'橡木楼梯',oak_slab:'橡木台阶',cobblestone_stairs:'圆石楼梯',stone_brick_stairs:'石砖楼梯',stone_slab:'石头台阶',cobblestone_slab:'圆石台阶',oak_sign:'橡木告示牌',oak_wall_sign:'橡木墙上告示牌',oak_hanging_sign:'橡木悬挂告示牌',ladder:'梯子',vine:'藤蔓',glow_lichen:'发光地衣',chain:'锁链',iron_bars:'铁栏杆',spawner_side:'刷怪笼(侧)',end_portal:'末地传送门',end_portal_frame:'末地传送门框架',end_gateway:'末地折跃门',end_rod:'末地烛',chorus_plant:'紫颂植株',chorus_flower:'紫颂花',purpur_pillar:'紫珀柱',dragon_egg:'龙蛋',nether_portal:'下界传送门',magma_block:'岩浆块',soul_fire:'灵魂火',fire:'火',water:'水',water_still:'静水',water_flow:'流水',water_overlay:'水面覆盖',lava:'熔岩',lava_still:'静熔岩',lava_flow:'熔岩流',ice:'冰',packed_ice:'浮冰',blue_ice:'蓝冰',frosted_ice:'霜冰',snow:'雪',powder_snow:'细雪',snow_block:'雪块',crying_obsidian:'哭泣的黑曜石',obsidian:'黑曜石',bedrock:'基岩',netherrack:'下界岩',nylium:'菌岩',crimson_nylium:'绯红菌岩',warped_nylium:'诡异菌岩',nether_sprouts:'下界苗',crimson_roots:'绯红菌索',warped_roots:'诡异菌索',basalt_side:'玄武岩(侧)',polished_basalt:'磨制玄武岩',shroomlight_block:'菌光体方块',soul_soul:'灵魂沙',cobweb:'蜘蛛网',destroy_stage:'破坏阶段',
dandelion:'蒲公英',poppy:'虞美人',blue_orchid:'蓝色兰花',allium:'绒球葱',azure_bluet:'茜草花',red_tulip:'红色郁金香',orange_tulip:'橙色郁金香',white_tulip:'白色郁金香',pink_tulip:'粉红色郁金香',oxeye_daisy:'滨菊',cornflower:'矢车菊',lily_of_the_valley:'铃兰',wither_rose:'凋零玫瑰',sunflower:'向日葵',lilac:'丁香',rose_bush:'玫瑰丛',peony:'牡丹',torchflower_crop:'火把花苗',pink_petals:'粉红色花簇',spore_blossom:'孢子花',big_dripleaf:'大型垂滴叶',small_dripleaf:'小型垂滴叶',glowstone_dust:'荧石粉',hanging_roots:'垂根',oak_sapling:'橡树树苗',spruce_sapling:'云杉树苗',birch_sapling:'白桦树苗',cherry_sapling:'樱花树苗',bamboo_sapling:'竹笋',red_mushroom:'红色蘑菇',brown_mushroom:'棕色蘑菇',crimson_fungus:'绯红菌',warped_fungus:'诡异菌',weeping_vines:'垂泪藤',twisting_vines:'缠怨藤',nether_vines:'下界藤蔓',cave_vines:'洞穴藤蔓',glow_berries:'发光浆果',seagrass:'海草',tall_seagrass:'高海草',kelp:'海带',kelp_plant:'海带植物',sea_lantern_side:'海晶灯(侧)',tube_coral:'管珊瑚',brain_coral:'脑纹珊瑚',bubble_coral:'气泡珊瑚',fire_coral:'火珊瑚',horn_coral:'鹿角珊瑚',dead_bush:'枯灌木',fern:'蕨',large_fern:'大型蕨',tall_grass:'高草丛',short_grass:'草丛',grass:'草(旧版)',azalea:'杜鹃花丛',flowering_azalea:'盛开的杜鹃花丛',mangrove_propagule:'红树胎生苗',mangrove_roots:'红树根',pale_oak_log:'苍白橡木原木',pale_oak_planks:'苍白橡木木板',pale_moss_block:'苍白苔藓块',creaking_heart:'嘎枝之心',
copper_grate:'铜格栅',chiseled_copper:'錾制铜',copper_door:'铜门',copper_trapdoor:'铜活板门',chiseled_tuff:'錾制凝灰岩',tuff_bricks:'凝灰岩砖',trial_spawner:'试炼刷怪笼',trial_key:'试炼钥匙',breeze_rod:'旋风棒',heavy_core:'重质核心',
/* ---- 物品 ---- */
diamond:'钻石',emerald:'绿宝石',iron_ingot:'铁锭',gold_ingot:'金锭',copper_ingot:'铜锭',netherite_ingot:'下界合金锭',netherite_scrap:'下界合金碎片',coal:'煤炭',charcoal:'木炭',lapis_lazuli:'青金石',redstone:'红石粉',quartz:'下界石英',amethyst_shard:'紫水晶碎片',echo_shard:'回响碎片',iron_nugget:'铁粒',gold_nugget:'金粒',raw_iron:'粗铁',raw_copper:'粗铜',raw_gold:'粗金',stick:'木棍',bone:'骨头',bone_meal:'骨粉',string:'线',feather:'羽毛',flint:'燧石',leather:'皮革',rabbit_hide:'兔子皮',paper:'纸',book:'书',enchanted_book:'附魔书',writable_book:'书与笔',name_tag:'命名牌',lead:'拴绳',saddle:'鞍',gunpowder:'火药',blaze_powder:'烈焰粉',blaze_rod:'烈焰棒',breeze_powder:'旋风粉',ender_pearl:'末影珍珠',ender_eye:'末影之眼',ghast_tear:'恶魂之泪',nether_star:'下界之星',prismarine_shard:'海晶碎片',prismarine_crystals:'海晶砂粒',shulker_shell:'潜影壳',turtle_scute:'海龟鳞甲',armadillo_scute:'犰狳鳞甲',phantom_membrane:'幻翼膜',heart_of_the_sea:'海洋之心',nautilus_shell:'鹦鹉螺壳','sculk_tendril':'幽匿触须',disc_fragment:'唱片残片',netherite_upgrade_smithing_template:'下界合金升级锻造模板',smithing_template:'锻造模板',trial_key_2:'试炼钥匙',
diamond_sword:'钻石剑',diamond_pickaxe:'钻石镐',diamond_axe:'钻石斧',diamond_shovel:'钻石铲',diamond_hoe:'钻石锄',iron_sword:'铁剑',iron_pickaxe:'铁镐',iron_axe:'铁斧',iron_shovel:'铁铲',iron_hoe:'铁锄',golden_sword:'金剑',golden_pickaxe:'金镐',golden_axe:'金斧',golden_shovel:'金铲',golden_hoe:'金锄',stone_sword:'石剑',stone_pickaxe:'石镐',stone_axe:'石斧',stone_shovel:'石铲',stone_hoe:'石锄',wooden_sword:'木剑',wooden_pickaxe:'木镐',wooden_axe:'木斧',wooden_shovel:'木铲',wooden_hoe:'木锄',netherite_sword:'下界合金剑',netherite_pickaxe:'下界合金镐',netherite_axe:'下界合金斧',netherite_shovel:'下界合金铲',netherite_hoe:'下界合金锄',bow:'弓',crossbow:'弩',arrow:'箭',spectral_arrow:'光灵箭',tipped_arrow:'药水箭',trident:'三叉戟',shield:'盾牌',elytra:'鞘翅',shears:'剪刀',flint_and_steel:'打火石',fishing_rod:'钓鱼竿',carrot_on_a_stick:'胡萝卜钓竿',warped_fungus_on_a_stick:'诡异菌钓竿',brush:'刷子',spyglass:'望远镜',compass:'指南针',recovery_compass:'追溯指针',clock:'时钟',map:'地图',empty_map:'空地图',bundle:'收纳袋',
diamond_helmet:'钻石头盔',diamond_chestplate:'钻石胸甲',diamond_leggings:'钻石护腿',diamond_boots:'钻石靴子',iron_helmet:'铁头盔',iron_chestplate:'铁胸甲',iron_leggings:'铁护腿',iron_boots:'铁靴子',golden_helmet:'金头盔',golden_chestplate:'金胸甲',golden_leggings:'金护腿',golden_boots:'金靴子',leather_helmet:'皮革帽子',leather_chestplate:'皮革外套',leather_leggings:'皮革裤子',leather_boots:'皮革靴子',netherite_helmet:'下界合金头盔',netherite_chestplate:'下界合金胸甲',netherite_leggings:'下界合金护腿',netherite_boots:'下界合金靴子',turtle_helmet:'海龟壳',armadillo_helmet_layer:'犰狳头盔',
apple:'苹果',golden_apple:'金苹果',enchanted_golden_apple:'附魔金苹果',bread:'面包',cooked_beef:'牛排',beef:'生牛肉',cooked_porkchop:'熟猪排',porkchop:'生猪排',cooked_chicken:'熟鸡肉',chicken:'生鸡肉',cooked_mutton:'熟羊肉',mutton:'生羊肉',cooked_rabbit:'熟兔肉',rabbit:'生兔肉',cod:'鳕鱼',cooked_cod:'熟鳕鱼',salmon:'鲑鱼',cooked_salmon:'熟鲑鱼',tropical_fish:'热带鱼',pufferfish:'河豚',rotten_flesh:'腐肉',spider_eye:'蜘蛛眼',carrot:'胡萝卜',golden_carrot:'金胡萝卜',potato:'马铃薯',baked_potato:'烤马铃薯',poisonous_potato:'毒马铃薯',beetroot:'甜菜根',beetroot_soup:'甜菜汤',mushroom_stew:'蘑菇煲',rabbit_stew:'兔肉煲',suspicious_stew:'迷之炖菜',cookie:'曲奇',pumpkin_pie:'南瓜派',cake_item:'蛋糕',dried_kelp:'干海带',sweet_berries:'甜浆果',glow_berries_item:'发光浆果',honey_bottle:'蜂蜜瓶',honeycomb:'蜜脾',milk_bucket:'牛奶桶',water_bucket:'水桶',lava_bucket:'熔岩桶',bucket:'铁桶',milk:'牛奶',experience_bottle:'附魔之瓶',
potion:'药水',splash_potion:'喷溅药水',lingering_potion:'滞留药水',glass_bottle:'玻璃瓶',fermented_spider_eye:'发酵蛛眼',blaze_powder_2:'烈焰粉',nether_wart_item:'下界疣',red_nether_brick_stairs:'红色下界砖楼梯',sugar:'糖',egg:'鸡蛋',blue_egg:'蓝色鸡蛋',brown_egg:'棕色鸡蛋',turtle_helmet_layer:'海龟壳层',snowball:'雪球',ender_dragon_egg_item:'龙蛋',totem_of_undying:'不死图腾',totem:'图腾',experience_orb:'经验球',firework_rocket:'烟花火箭',firework_charge:'烟花之星',item_frame:'物品展示框',glow_item_frame:'荧光物品展示框',painting:'画',armor_stand:'盔甲架',flower_pot:'花盆',skull:'头颅',player_head:'玩家头',zombie_head:'僵尸头',creeper_head:'苦力怕头',skeleton_skull:'骷髅头颅',wither_skeleton_skull:'凋灵骷髅头颅',dragon_head:'龙首',piglin_head:'猪灵头',custom_head:'自定义头颅',music_disc:'唱片',music_disc_cat:'唱片cat',music_disc_pigstep:'唱片Pigstep',music_disc_otherside:'唱片otherside',music_disc_5:'唱片5',goat_horn:'山羊角',wind_charge:'风弹',ominous_bottle:'不祥之瓶',mace:'重锤',
/* ---- 实体(目录名) ---- */
allay:'悦灵',axolotl:'美西螈',bat:'蝙蝠',bee:'蜜蜂',blaze:'烈焰人',breeze:'旋风人',camel:'骆驼',cat:'猫',cave_spider:'洞穴蜘蛛',chicken:'鸡',cod:'鳕鱼',creeper:'苦力怕',dolphin:'海豚',donkey:'驴',dragon:'龙',drowned:'溺尸',elder_guardian:'远古守卫者',enderman:'末影人',endermite:'末影螨',evoker:'唤魔者',fox:'狐狸',frog:'青蛙',ghast:'恶魂',giant:'巨人',glow_squid:'发光鱿鱼',goat:'山羊',guardian:'守卫者',hoglin:'疣猪兽',horse:'马',husk:'尸壳',illusioner:'幻术师',iron_golem:'铁傀儡',llama:'羊驼',magma_cube:'岩浆怪',mooshroom:'哞菇',mule:'骡',ocelot:'豹猫',panda:'熊猫',parrot:'鹦鹉',phantom:'幻翼',pig:'猪',piglin:'猪灵',piglin_brute:'猪灵蛮兵',pillager:'掠夺者',polar_bear:'北极熊',pufferfish:'河豚',rabbit:'兔子',ravager:'劫掠兽',salmon:'鲑鱼',sheep:'羊',shulker:'潜影贝',silverfish:'蠹虫',skeleton:'骷髅',skeleton_horse:'骷髅马',slime:'史莱姆',sniffer:'嗅探兽',snow_golem:'雪傀儡',spider:'蜘蛛',squid:'鱿鱼',stray:'流浪者',strider:'炽足兽',tadpole:'蝌蚪',trader_llama:'行商羊驼',tropical_fish:'热带鱼',turtle:'海龟',vex:'恼鬼',villager:'村民',vindicator:'卫道士',wandering_trader:'流浪商人',warden:'监守者',witch:'女巫',wither:'凋灵',wither_skeleton:'凋灵骷髅',wolf:'狼',zoglin:'僵尸疣猪兽',zombie:'僵尸',zombie_horse:'僵尸马',zombie_villager:'僵尸村民',zombified_piglin:'僵尸猪灵',player:'玩家',steve:'Steve',alex:'Alex',creeper_charge:'苦力怕爆炸',guardian_beam:'守卫者光束',sign:'告示牌',chest_boat:'运输船',boat:'船',minecart:'矿车',armor_stand_minor:'盔甲架部件',spider_eyes:'蜘蛛眼',saddles:'鞍具',wolf_collar:'狼项圈',cat_collar:'猫项圈',sheep_fur:'羊毛',sheep_face:'羊脸',villager_profession:'村民职业',iron_golem_crack:'铁傀儡裂纹',shulker_bullet:'潜影贝导弹',
/* ---- 粒子 ---- */
angry:'怒气',bubble:'气泡',bubble_pop:'气泡破裂',campfire_cosy_smoke:'营火炊烟',campfire_signal_smoke:'营火信号烟',cherry_leaves:'樱花叶',cloud:'云',crit:'暴击',damage:'伤害',dripping_dripstone_lava:'钟乳石滴熔岩',dripping_dripstone_water:'钟乳石滴水',dripping_honey:'滴蜂蜜',dripping_lava:'滴熔岩',dripping_obsidian_tear:'滴黑曜石泪',dripping_water:'滴水',dust:'粉尘',dust_pillar:'尘柱',effect:'效果',elder_guardian:'远古守卫者',electrical_spark:'电火花',enchant:'附魔',end_rod:'末地烛光尘',entity_effect:'实体效果',explosion:'爆炸',explosion_emitter:'大爆炸',falling_dripstone_lava:'钟乳石落熔岩',falling_dripstone_water:'钟乳石落水',falling_dust:'落尘',falling_honey:'落蜂蜜',falling_lava:'落熔岩',falling_nectar:'落花蜜',falling_obsidian_tear:'落黑曜石泪',falling_spore_blossom:'落孢子花',falling_water:'落水',firework:'烟花',fishing:'钓鱼',flame:'火焰',flash:'闪光',glint:'闪光效果',glow:'发光',gust:'风爆',gust_emitter_large:'大风爆',gust_emitter_small:'小风爆',happy:'快乐',heart:'心',infested:'被感染',instant_effect:'立即效果',landing_honey:'蜂蜜落地',landing_lava:'熔岩落地',landing_obsidian_tear:'黑曜石泪落地',large_explosion:'大爆炸',large_smoke:'大烟雾',lava:'熔岩滴',mycelium:'菌丝',nautilus:'鹦鹉螺',note:'音符',ominous_spawning:'不祥生成',poof:'消散 smoke',portal:'传送门',rain:'雨',reverse_portal:'反向传送门',scrape:'刮削',sculk_charge:'幽匿充能',sculk_charge_pop:'幽匿充能爆',sculk_soul:'幽匿之魂',server_buster:'服务器破坏者',small_flame:'小火焰',small_gust:'小风爆',smoke:'烟雾',sneeze:'喷嚏',snowflake:'雪花',sonic_boom:'音波',soul:'灵魂',soul_fire_flame:'灵魂火焰',spark:'火花',spit:'喷吐',splash:'溅落',spore_blossom_air:'孢子花空气',squid_ink:'鱿鱼墨汁',suspended:'悬浮',sweep_attack:'横扫攻击',totem_of_undying:'不死图腾',trail:'轨迹',trial_omen:'试炼之兆',trial_spawner_detection:'试炼侦测',underwater:'水下',vibration:'震动',warped_spore:'诡异孢子',wax:'涂蜡',white_ash:'白灰',witch:'女巫',dripping_dripstone:'钟乳石滴落',big_smoke:'大烟雾粒子',generic:'通用粒子纹理',particle:'粒子',
/* ---- GUI ---- */
gui:'界面',icons:'状态图标',hud:'HUD',hotbar:'物品栏',heart:'生命值心',heart_container:'生命值容器',food:'饥饿值',armor:'护甲值',bubbles:'氧气泡',experience_bar:'经验条',crosshair:'准星',background:'背景',button:'按钮',button_highlight:'按钮高亮',container:'容器',creative_inventory:'创造模式物品栏',inventory:'物品栏',widgets:'小部件',banner_base:'旗帜底',effects:'状态效果',recipe_book:'配方书',advancements:'进度',toasts:'弹窗提示',social_interactions:'社交互动',pause_screen:'暂停界面',title:'标题界面',options_background:'选项背景',panorama:'全景图',unknown_pack:'未知包',missing_texture:'缺失纹理',debug:'调试',split:'分屏',realm:'Realms',slider:'滑块',text_field:'文本框',checkbox:'复选框',tab:'标签页',tooltip:'提示框',dialog:'对话框',loading:'加载中',join:'加入',quick_actions:'快捷操作',sign:'签名',loom:'织布机界面',stonecutter:'切石机界面',anvil_screen:'铁砧界面',blast_furnace:'高炉界面',smoker_screen:'烟熏炉界面',beacon_screen:'信标界面',brewing_stand:'酿造台界面',crafting_table_screen:'工作台界面',furnace_screen:'熔炉界面',hopper_screen:'漏斗界面',horse_screen:'马界面',inventory_screen:'物品栏界面',shulker_box_screen:'潜影盒界面',dispenser_screen:'发射器界面',enchanting_table_book:'附魔台书',vignette:'晕影',powder_snow_outline:'细雪轮廓',spyglass_scope:'望远镜镜筒',crosshair_attack_indicator:'攻击指示条',experience_orb_gui:'经验球界面',
/* ---- 其他常见 ---- */
painting:'画',map_on_map:'地图底图',map_background:'地图背景',trims:'盔甲纹饰',colormap:'颜色映射',grass_colormap:'草色映射',foliage_colormap:'树叶色映射',font:'字体',ascii:'ASCII字体',accented:'重音字符',nonlatin_european:'非拉丁欧洲字符',misc:'杂项',mob_effect:'状态效果图标',environment:'环境',sun:'太阳',moon:'月亮',moon_phases:'月相',clouds:'云',end_sky:'末地天空',end_beam:'末地光柱',nether:'下界',sky:'天空',stars:'星星',void:'虚空',rain_snow:'雨雪',destroy:'破坏动画',shadow:'阴影',enchant_glyph:'附魔字符',custom:'自定义',cem:'自定义实体模型',cit:'自定义物品纹理',overlay:'叠层',fog:'雾'
};
/* 反查兜底:常用词根 */
const ZH_FALLBACK = [
  [/^deepslate_(.+)_ore$/, '深层$1矿'], [/_ore$/, '矿石'], [/_planks$/, '木板'], [/_log$/, '原木'], [/_wood$/, '木'],
  [/_leaves$/, '树叶'], [/_sapling$/, '树苗'], [/_door$/, '门'], [/_trapdoor$/, '活板门'], [/_fence$/, '栅栏'],
  [/_stairs$/, '楼梯'], [/_slab$/, '台阶'], [/_button$/, '按钮'], [/_wall$/, '墙'], [/_glass$/, '玻璃'],
  [/_wool$/, '羊毛'], [/_carpet$/, '地毯'], [/_bed$/, '床'], [/_banner$/, '旗帜'], [/_concrete(_powder)?$/, '混凝土'],
  [/_terracotta$/, '陶瓦'], [/_candle$/, '蜡烛'], [/_sign$/, '告示牌'], [/_shulker_box$/, '潜影盒'],
  [/^white_/, '白色'], [/^orange_/, '橙色'], [/^magenta_/, '品红色'], [/^light_blue_/, '淡蓝色'], [/^yellow_/, '黄色'],
  [/^lime_/, '黄绿色'], [/^pink_/, '粉红色'], [/^gray_/, '灰色'], [/^light_gray_/, '淡灰色'], [/^cyan_/, '青色'],
  [/^purple_/, '紫色'], [/^blue_/, '蓝色'], [/^brown_/, '棕色'], [/^green_/, '绿色'], [/^red_/, '红色'], [/^black_/, '黑色'],
  [/_sword$/, '剑'], [/_pickaxe$/, '镐'], [/_axe$/, '斧'], [/_shovel$/, '铲'], [/_hoe$/, '锄'], [/_helmet$/, '头盔'],
  [/_chestplate$/, '胸甲'], [/_leggings$/, '护腿'], [/_boots$/, '靴子'], [/bucket$/, '桶'], [/_boat$/, '船']
];
function zhName(base){
  if (ZH[base]) return ZH[base];
  for (const [re, rep] of ZH_FALLBACK) {
    if (re.test(base) && rep.includes('$1')) return base.replace(re, rep);
  }
  return null;
}
